language: node_js
node_js: 
- "0.10"
before_install: 
- npm install -g grunt-cli
env: 
  global: 
    secure: V3BBHCGRaFLuObaoFU80v+6O2GODN8RZxDD/EAolMm9qQ8nbqZmtW7+x6Uu0QR8eWGDswGHSjwX/1cG66wwCIteZVzMGhIYP4pXozSX22yQnwaYb9orfmXGgrdY9jxVYWeKk9iASXppOIMRou+UG+tWjKcfLObnqLsxNfEr20p0=
